Traceback (most recent call last):
  File "/Users/virginie/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/virginie/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/virginie/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/virginie/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/virginie/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/virginie/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/virginie/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/virginie/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
styles = [('dash dotted', (0, (3, 5, 1 ,5))),
        ('loosely dashdotted', (0, (3, 10, 1, 10))),
        ('densly dashdotted', (0, (3, 1, 1, 1)))]

y = np.array([1, 1])
for s in styles:
    plt.plot(y, linestyle=s[1], label=s[0], color='black')
    plt.text(0, y[0]+0.2, s[0])
    y += 1
    
plt.ylim(0, 4)
plt.gca().set_yticklabels(yticks)
plt.tick_params(left=False, bottom=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-6-1d134668a77d>[0m in [0;36m<module>[0;34m[0m
[1;32m     10[0m [0;34m[0m[0m
[1;32m     11[0m [0mplt[0m[0;34m.[0m[0mylim[0m[0;34m([0m[0;36m0[0m[0;34m,[0m [0;36m4[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 12[0;31m [0mplt[0m[0;34m.[0m[0mgca[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mset_yticklabels[0m[0;34m([0m[0myticks[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     13[0m [0mplt[0m[0;34m.[0m[0mtick_params[0m[0;34m([0m[0mleft[0m[0;34m=[0m[0;32mFalse[0m[0;34m,[0m [0mbottom[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'yticks' is not defined
NameError: name 'yticks' is not defined

